app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    
    pass_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog', backref='user', lazy="dynamic")
    comments = db.relationship('Comment',backref = 'user',lazy="dynamic")

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        reviews = Comment.query.filter_by(blog_id=id).all()
        return comments

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username}'


class Blog(db.Model):
    
    __tablename__ = 'blog'

    id = db.Column(db.Integer,primary_key = True)
    blog = db.Column(db.String)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'blog',lazy="dynamic")

    def save_blog(self):
        '''
        Function that saves blogs
        '''
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_all_blogs(cls):
       
        return Blog.query.all()

    @classmethod
    def get_blogs_by_blog(cls,blo_id):
        
        return Blog.query.filter_by(blog_id= blo_id)


class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment= db.Column(db.String)
    blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
  

    def save_comment(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def clear_comments(cls):
        Comment.all_comments.clear()

    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(blog_id=id).all()

        return comments

class Quotes:
    def __init__(self,author,quote):
        self.author = author
        self.quote = quote

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError, SelectField, RadioField
from wtforms.validators import Required,Email
from ..models import User


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentsForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('SUBMIT')   

class BlogForm(FlaskForm):
    content = TextAreaField('YOUR BLOG')
    submit = SubmitField('Create Blog')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

photos = UploadSet('photos',IMAGES)
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
simple = SimpleMDE()

def create_app(config_name):

    app = Flask(__name__)

    # Initializing flask extensions
    bootstrap.init_app(app)
    
    login_manager.init_app(app)
    mail.init_app(app)
    # simple.init_app(app)
     # Creating the app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)
    db.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template, request, redirect, url_for,abort
from . import main
from .forms import UpdateProfile 
from .forms import CommentsForm, UpdateProfile, BlogForm
from ..request import get_quotes
from ..models import User,Blog,Comment
from flask_login import login_required,current_user
from .. import db,photos
import markdown2 


# Views
@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''

    title = 'Home - Welcome to The Blogging'

    blog= Blog.query.all()
    quotes= get_quotes()  

    return render_template('index.html', title = title,quotes=quotes, blog= blog)
   

@main.route('/blog/new/', methods = ['GET','POST'])
@login_required
def new_blog():
    '''
    Function that creates new blogs
    '''
    form = BlogForm()
    if form.validate_on_submit():
        blog = form.content.data
        new_blog= Blog(blog = blog)

        new_blog.save_blog()
        return redirect(url_for('main.index'))

    return render_template('new_blog.html', new_blog_form= form)

@main.route('/blog/<int:id>/update',methods = ['GET','POST'])
@login_required
def update_blog(id):
    blog=Blog.query.get(id)
    print(blog.blog)
    if blog is None:
        abort(404)
    form=BlogForm()
    if form.validate_on_submit():
        blog.blog=form.content.data
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('.index'))
    elif request.method == 'GET':
        form.content.data = blog.blog

    return render_template('blog.html', form=form)

@main.route('/blog/comments/new/<int:id>',methods = ['GET','POST'])
@login_required
def new_comment(id):
    form = CommentsForm()
    if form.validate_on_submit():
        comment=form.comment.data
        print(comment)
        new_comment = Comment(user=current_user, comment = comment)
        new_comment.save_comment()
        return redirect(url_for('main.index'))
    comments = Comment.get_comments(id)
    print(comments)
    comm=Comment.query.filter_by(id = id).all()
    print(comm)
    return render_template('new_comment.html',comment_form=form,comm = comm)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path 
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))
    
    return render_template('profile/update.html',form =form)

@main.route('/index/<int:id>/delete', methods = ['GET','POST',])
@login_required
def delete(id):
   current_post = Blog.query.get(id)
   print(current_post)
   db.session.delete(current_post)
   db.session.commit()
   return redirect(url_for('main.index'))
   
@main.route('/index/<int:id>/delete_comment', methods = ['GET','POST'])
@login_required
def delete_comment(id):
   current_post = Comment.query.filter_by(id = id).first()
   if current_post.user != current_user:
       abort(404)
   db.session.delete(current_post)
   db.session.commit()
   return redirect(url_for('.index'))
#    return render_template('comments.html',current_post = current_post)

@main.route('/test/<int:id>')  
def test(id):
    '''
    this is route for basic testing
    '''
    blog =blog.query.filter_by(id=1).first()

    return render_template('test.html',Blog = Blog)

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best place of posting  your blog!! </title>
        {% endif %} 
        {% extends 'bootstrap/base.html'%}

        <!-- Navbar block  --> 
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/blog.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content%}
    <div class="container">
        <a href="{{url_for('main.index')}}">
                <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                        <span class="glyphicon glyphicon-chevron-left" ></span> Back
                </button>
        </a>
        {{wtf.quick_form(form)}}
    </div>

   
{% endblock %}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content%}
<div class="container-fluid">

  <div class="row">
    <div class="col-sm-4">
      <img src="{{comment.image_path}}" class="img-responsive">
    </div>

    <div class="col-sm-8">
      {{wtf.quick_form(form)}}
    </div>
  </div>
</div>
{%endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block styles%}
{{ super() }}
<link href="https://fonts.googleapis.com/css?family=Akronim|Bellefair|Joti+One" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}
<div class="container"
    style="background-image: url(https://cdn.pixabay.com/photo/2019/04/24/11/27/flowers-4151900_960_720.jpg);background-repeat: no-repeat; background-attachment: fixed; background-position: center top; margin-top:0px; padding-top:40px; padding-bottom:400px;">
    <div class="row" style="text-align:center; font-size:10px;">
        <span style="font-size:40px; font-family: 'serif', cursive; color: rgb(22, 25, 78);"><strong>Post Your Blog
                Here</strong> </span>
    </div>
    <div class="row" style="text-align:center; font-size:25px;">
        <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-9" style="padding-left:300px;">
            <div class="panel"
                style="border: 3px solid #f2f2f2; padding:20px; margin-top:10px; background-image: url(https://image.freepik.com/free-photo/old-wooden-texture-background-vintage_55716-1138.jpg);background-position: center top;">
                <a href="{{url_for('main.new_blog')}}">
                    <br>
                    <button type="button" class="btn btn-outline-primary btn-sm"
                        style="font-size:18px;margin-bottom:30px;"> <span>Post new Blog </span></button>
                </a>
                <div class="blog" style="color:#d8d1d1;">
                    <p>{{macro.displayBlog(blog)}} </p>
                </div>
                

            </div>
            <div class="row" style="text-align:center; font-size:25px;">
                <span
                    style="font-size:40px; font-family: 'serif', cursive; color: rgb(22, 25, 78);"><strong>Quotes</strong>
                </span>
                <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-9" style="padding:20px; margin-top:10px;">
                    <div class="panel"style="border: 3px solid #f2f2f2; width:560px; background-image: url(https://image.freepik.com/free-photo/old-wooden-texture-background-vintage_55716-1138.jpg);">
                       <div class="para" style="color:#d8d1d1">
                        <p><i>{{ quotes.quote }}</i></p>
                        <p>{{quotes.author}}</p>
                       </div>
                        
                    </div>

                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

app/templates/macros.html
{% macro displayBlog(blogs_list) %}

{% for blog in blogs_list %}
<div class="panel style=" style="box-shadow: 3px 3px 3px 3px #a3a2a2; padding:10px; text-align:center;background: transparent;">
  <p>{{blog.blog}}</p>
  <br>
    <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-comment"><a href="{{url_for('main.new_comment',id=blog.id)}}"></span> Comment</a></button>
    <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-trash"><a href="{{url_for('main.delete',id=blog.id)}}"></span> Trash </a></button>
    <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-edit"><a href="{{url_for('main.update_blog',id=blog.id)}}"></span> Edit</a></button>
</div>
{% endfor %}
{% endmacro %}

{% macro displayComments(Comments_list) %}

{% for blog in Comments_list %}
<div class="panel" style="box-shadow: 5px 5px 5px 5px #f2f2f2; padding:10px; text-align:center;">
  <p>{{blog.comment}}</p>
  
</div>
{% endfor %}

{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation" style="background-color: rgb(31, 6, 21);">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> <strong>Blog</strong> </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"> <span>Home</span> </a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content%}
    <div class="container">
        <a href="{{url_for('main.index')}}">
                <button type="button" class="btn btn-primary btn-sm" style="margin-bottom:10px;">
                        <span class="glyphicon glyphicon-chevron-left" ></span> Back
                </button>
        </a>
        {{wtf.quick_form(new_blog_form)}}
    </div>

   
{% endblock %}

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
        <div class="col-md-3 col-lg-3 col-xl-3">
        </div>

        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 ">
                {{ wtf.quick_form(comment_form) }}

        </div>
        <div class="col-md-3 col-lg-3 col-xl-3" >
                <h2>comments:</h2>

                {{macro.displayComments(comm)}}
        </div>


</div>

</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p style="color: rgb(13, 19, 102);font-size: 19px; ">No profile picture</p>
            {% endif %}
            {% if user == current_user %}
            <form action="{{url_for('main.update_profile',uname=user.username)}}" method="post"
                enctype="multipart/form-data">Edit profile</a>
                <input type="file" name="photo">
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}